Repository airbnb/polyglot.js, pull requests merged in 2018-06, with the labels that each got.

#112 Fix Issue #110 : Remove false sentence
  README.md
Labels: docs

#114 Add more test for croatian and added locale
  index.js
  test/index.js
Labels: semver-patch: bugfixes/refactors/etc

#113 Add support for new languages.
  index.js
  test/index.js
Labels: semver-minor: new stuff

#64 Add option to modify the tokenPattern used to replace the interpolations
  README.md
  index.js
  test/index.js
Labels: feature request, pull request wanted

#106 Interpolation options
  README.md
  index.js
  test/index.js
Labels: semver-minor: new stuff
